### ISSUE TITLE
Big pipes

### ISSUE THREAD

**Issue by sergio-mm** [gilesp1729/Tubemiter#1]
The software is fantastic. Thanks for it.

If the size of the tube is greater than a sheet of paper, what can we do?

For example, a pair of pipes of 500mm of diameter.

**Comment by gilesp1729** [comment]
Make sure Acrobat Reader is installed. Choose Print to PDF, using a paper size big enough to go round the tube (like A0). Then open the PDF file in Acrobat and print it to the real printer using the Tile Large Pages option. That should work (I have done it with other apps and it was OK)

**Comment by sergio-mm** [comment]
How I could not thought out it!!!

In big  pipe sizes only appears in screen a fraction of the paper to print, but it works like a charm.

And, if you have troubles with the pipes, interchange them in Settings in order to achieve a proper print. 

Thank you very much for show me path to the solution.
